"""Controlled schema definitions for Phase 2 OSM standardization."""

ROAD_STANDARDIZED_FIELDS = [
    "road_edge_id",
    "osm_id_raw",
    "source_u",
    "source_v",
    "source_key",
    "road_name",
    "road_class_source",
    "road_class_standard",
    "maxspeed_raw",
    "maxspeed_mph",
    "lanes_raw",
    "lanes_count",
    "oneway_raw",
    "oneway_standard",
    "surface_raw",
    "access_raw",
    "service_raw",
    "bridge_raw",
    "tunnel_raw",
    "junction_raw",
    "reversed_raw",
    "source_length_m",
    "geometry_length_ft",
    "geometry_length_m",
    "geometry_valid",
    "source_dataset",
    "extraction_timestamp_utc",
    "standardization_status",
    "standardization_notes",
    "geometry",
]

BUILDING_STANDARDIZED_FIELDS = [
    "building_feature_id",
    "osm_id_raw",
    "element_type",
    "building_name",
    "building_type_source",
    "building_type_standard",
    "building_levels_raw",
    "building_levels_count",
    "address_number",
    "address_street",
    "address_city",
    "address_postcode",
    "amenity_raw",
    "shop_raw",
    "office_raw",
    "landuse_raw",
    "area_sqft",
    "area_sqm",
    "geometry_valid",
    "source_dataset",
    "extraction_timestamp_utc",
    "standardization_status",
    "standardization_notes",
    "geometry",
]

EXCEPTION_FIELDS = [
    "dataset_name",
    "source_record_id",
    "field_name",
    "source_value",
    "exception_type",
    "severity",
    "action_taken",
    "review_required",
]

FIELD_INVENTORY_FIELDS = [
    "dataset_name",
    "field_name",
    "source_dtype",
    "total_record_count",
    "non_null_count",
    "null_count",
    "percent_complete",
    "unique_value_count",
    "sample_values",
    "contains_list_like_values",
    "contains_json_like_values",
    "notes",
]
